# Generated by Django 3.0.7 on 2020-06-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='ip',
            field=models.TextField(),
        ),
    ]
